name: Docker Build And Push

on:
  push:
    branches:
      - "release"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dummy-go:${{github.run_number}}

      # - name: Send Deployment Request To Jenkins
      #   uses: wei/curl@v1
      #   with:
      #     args: <jenkins_server_ip>/generic-webhook-trigger/invoke -d 'token=${{secrets.JENKINS_TOKEN}}&version=${{github.run_number}}'
