name: Docker Build And Push

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devenes/dummy-go:${{github.run_number}}
      - name: Send Deployment Request To Jenkins
        uses: wei/curl@v1
        with:
          args: http://44.192.40.115:8080/generic-webhook-trigger/invoke -d 'token=${{secrets.JENKINS_TOKEN}}&version=${{github.run_number}}'          
          # args: https://jsonplaceholder.typicode.com/todos/1
          # Add here your Jenkins Webhook link and the token you generated for Jenkins on your server.
          